Add files via upload

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,19 +1,26 @@
-0x14-javascript-web_scraping
-# Transfer file `file` to a server
-#scp /path/to/file username@a:/path/to/destination
-# Handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@34.75.10.160:/tmp
-
-#If number of arguments is >= 3
-if [ $# -ge 3 ]
+#!/usr/bin/env bash
+# Checking for command-line argument
+if [ $# -lt 4 ]
 then
-    if [ $# -eq 3 ]
-    then
-        # No private key provided
-        scp -o StrictHostKeyChecking=no $1 $3@$2:~/ 
-    else
-        # Private key provided
-        scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
-    fi
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# Assigning Arguments to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  echo "FILE TRANSFER FAILED"
 fi
